"""add role in projectmember table 

Revision ID: 6d50aaa8b49c
Revises: 5226d8b399b6
Create Date: 2026-01-12 21:09:31.772415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d50aaa8b49c'
down_revision: Union[str, Sequence[str], None] = '5226d8b399b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'role')
    # ### end Alembic commands ###
